name: Publish to NPM

on:
    push:
        tags:
            - "*"
    workflow_dispatch:

jobs:
    publish:
        strategy:
            matrix:
                node-version: [16]
                os: [ubuntu-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@master
              with:
                  fetch-depth: 1
            - uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
                  registry-url: https://registry.npmjs.org
            - run: npm run init-submodules
            - run: npm install
            - run: npm run tsc
            - run: npm run test
            - run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
