name: Publish to NPM

on:
    push:
        tags:
            - "*"
    workflow_dispatch:

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 1
            - uses: actions/setup-node@v4
              with:
                  node-version: 22
                  registry-url: https://registry.npmjs.org
            - run: npm install
            - run: npm run tsc
            - run: npm run test
            - run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
