name: Test & Deploy

on:
    push:
        tags:
            - "*"
    workflow_dispatch:

jobs:
    upload-macos:
        strategy:
            fail-fast: false
            matrix:
                config:
                    - { node-version: 8, npm-version: 6 }
                    - { node-version: 9, npm-version: 6 }
                    - { node-version: 10, npm-version: 6 }
                    - { node-version: 11, npm-version: 6 }
                    - { node-version: 12, npm-version: 8 }
                    - { node-version: 13, npm-version: 8 }
                    - { node-version: 14, npm-version: 8 }
                    - { node-version: 15, npm-version: 8 }
                    - { node-version: 16, npm-version: 8 }
                    - { node-version: 17, npm-version: 8 }
                    - { node-version: 18, npm-version: 8 }
                    - { node-version: 20, npm-version: 10 }
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@master
              with:
                  fetch-depth: 1
            - uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.config.node-version }}
                  registry-url: https://registry.npmjs.org

            - name: Package prebuilt binary
              run: |
                  npm install -g npm@${{ matrix.config.npm-version }}
                  npm config set progress false
                  npm install --build-from-source
                  npm run package 2>&1
                  npm run tsc
                  npm run test
            - name: Upload release binary
              uses: alexellis/upload-assets@0.3.0
              env:
                  GITHUB_TOKEN: ${{ github.token }}
              with:
                  asset_paths: '["./build/stage/libxmljs/libxmljs/releases/download/**/*.tar.gz"]'

    upload-windows:
        strategy:
            fail-fast: false
            matrix:
                config:
                    - { node-version: 8, npm-version: 6 }
                    - { node-version: 9, npm-version: 6 }
                    - { node-version: 10, npm-version: 6 }
                    - { node-version: 11, npm-version: 6 }
                    - { node-version: 12, npm-version: 8 }
                    - { node-version: 13, npm-version: 8 }
                    - { node-version: 14, npm-version: 8 }
                    - { node-version: 15, npm-version: 8 }
                    - { node-version: 16, npm-version: 8 }
                    - { node-version: 17, npm-version: 8 }
                    - { node-version: 18, npm-version: 8 }
                    - { node-version: 20, npm-version: 10 }
        runs-on: windows-2019
        steps:
            - uses: actions/checkout@master
              with:
                  fetch-depth: 1
            - uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.config.node-version }}
                  registry-url: https://registry.npmjs.org

            - name: Package prebuilt binary
              run: |
                  npm install -g npm@${{ matrix.config.npm-version }}
                  npm config set msvs_version "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise" --global
                  npm config set progress false
                  npm install --build-from-source
                  npm run package 2>&1
                  npm run tsc
                  npm run test
            - name: Upload release binary
              uses: alexellis/upload-assets@0.3.0
              env:
                  GITHUB_TOKEN: ${{ github.token }}
              with:
                  asset_paths: '["./build/stage/libxmljs/libxmljs/releases/download/**/*.tar.gz"]'

    upload-linux-older:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                config:
                    - { node-version: 8 }
                    - { node-version: 9 }
                    - { node-version: 10 }
                    - { node-version: 11 }
                    - { node-version: 12 }
                    - { node-version: 13 }
                    - { node-version: 14 }
                    - { node-version: 15 }
                container-image: [x86_64]
        container:
            image: quay.io/pypa/manylinux2014_${{ matrix.container-image }}
            options: --user root
        steps:
            - uses: actions/checkout@v3
              with:
                  persist-credentials: false
                  submodules: true
            - name: Use Node.js ${{ matrix.config.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.config.node-version }}
                  cache: "npm"
            - run: ldd --version
            - run: npm install --unsafe-perm --build-from-source
            - run: npm run package 2>&1
            - run: npm run tsc
            - run: npm run test
            - name: Upload release binary
              uses: alexellis/upload-assets@0.3.0
              env:
                  GITHUB_TOKEN: ${{ github.token }}
              with:
                  asset_paths: '["./build/stage/libxmljs/libxmljs/releases/download/**/*.tar.gz"]'

    upload-linux-newer:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                config:
                    - { node-version: 16 }
                    - { node-version: 17 }
                    - { node-version: 18 }
                    - { node-version: 20 }
                container-image: [x86_64]
        container:
            image: quay.io/pypa/manylinux_2_28_${{ matrix.container-image }}
            env:
                PATH: /opt/python/cp36-cp36m/bin:/opt/python/cp37-cp37m/bin:/opt/python/cp38-cp38/bin:/opt/rh/devtoolset-2/root/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/python/cp35-cp35m/bin:/opt/python/cp36-cp36m/bin:/opt/python/cp37-cp37m/bin:/opt/python/cp38-cp38/bin:/opt/python/cp39-cp39/bin:/opt/rh/devtoolset-8/root/usr/bin
            options: --user root
        steps:
            - uses: actions/checkout@v3
              with:
                  persist-credentials: false
                  submodules: true
            - name: Use Node.js ${{ matrix.config.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.config.node-version }}
                  cache: "npm"
            - run: yum install -y gcc-c++
            - run: ldd --version
            - run: npm ci --build-from-source
            - run: npm run package 2>&1
            - run: npm run tsc
            - run: npm run test
            - name: Upload release binary
              uses: alexellis/upload-assets@0.3.0
              env:
                  GITHUB_TOKEN: ${{ github.token }}
              with:
                  asset_paths: '["./build/stage/libxmljs/libxmljs/releases/download/**/*.tar.gz"]'

    upload-arm-builds:
        strategy:
            fail-fast: false
            matrix:
                config:
                    - { node-version: 8, npm-version: 6 }
                    - { node-version: 9, npm-version: 6 }
                    - { node-version: 10, npm-version: 6 }
                    - { node-version: 11, npm-version: 6 }
                    - { node-version: 12, npm-version: 8 }
                    - { node-version: 13, npm-version: 8 }
                    - { node-version: 14, npm-version: 8 }
                    - { node-version: 15, npm-version: 8 }
                    - { node-version: 16, npm-version: 8 }
                    - { node-version: 17, npm-version: 8 }
                    - { node-version: 18, npm-version: 8 }
                    - { node-version: 20, npm-version: 10 }
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
              with:
                  fetch-depth: 1
            - name: List files
              run: ls -l
            - uses: uraimo/run-on-arch-action@v2
              name: Build artifact
              id: build
              with:
                  arch: aarch64
                  distro: ubuntu_latest
                  githubToken: ${{ github.token }}

                  setup: |
                      mkdir -p "${PWD}/build"

                  dockerRunArgs: |
                      --volume "${PWD}/build:/build"
                      --volume "${PWD}:/app"
                      --workdir "/app"

                  shell: /bin/bash

                  install: |
                      apt update
                      apt install -y curl python3 build-essential git
                      curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
                      source ~/.nvm/nvm.sh
                      nvm install v${{matrix.config.node-version}}
                      npm install -g npm@${{ matrix.config.npm-version }}

                  run: |
                      source ~/.nvm/nvm.sh
                      npm config set progress false
                      npm i @mapbox/node-pre-gyp node-gyp -g
                      chown -R `whoami` ./
                      git config --global --add safe.directory '*'

                      npm install --build-from-source --unsafe-perm
                      node-pre-gyp package 2>&1
                      npm run tsc
                      npm run test

            - name: Upload release binary
              uses: alexellis/upload-assets@0.3.0
              env:
                  GITHUB_TOKEN: ${{ github.token }}
              with:
                  asset_paths: '["./build/stage/libxmljs/libxmljs/releases/download/**/*.tar.gz"]'
